"""Offline geometry components for generating gaze depth priors."""

from .deca_flame import (
    DEFAULT_DECA_ROOT,
    DecaFlameConfig,
    DecaFlameExtractor,
    DecaFlameOutput,
    head_local_pose_parameters,
)
from .face_preprocess import (
    DEFAULT_DECA_CROP_SCALE,
    FACE_PREPROCESS_CHOICES,
    FACE_PREPROCESS_DECA,
    FACE_PREPROCESS_LEGACY,
    FaceCropTransform,
    build_face_crop_transform,
    prepare_deca_face_image,
)
from .pnp import (
    CROSSGAZE_CAMERA_MATRIX,
    CROSSGAZE_DIST_COEFFS,
    CROSSGAZE_IMAGE_HEIGHT_PX,
    CROSSGAZE_IMAGE_WIDTH_PX,
    DEFAULT_PNP_MAPPING,
    FLAME_LEFT_EYE_CANTHUS_INDICES,
    FLAME_RIGHT_EYE_CANTHUS_INDICES,
    MEDIAPIPE_PNP_LANDMARK_INDICES,
    PNP_GEOMETRY_VERSION,
    PnpCamera,
    PnpConfig,
    PnpFaceDepthResult,
    PnpPointMapping,
    ScaleEstimate,
    compute_eye_canthus_midpoints,
    compute_scale_estimate,
    solve_pnp_face_depth,
    validate_crossgaze_image_size,
)
from .iris_ipd import (
    IrisIpdReconstruction,
    assign_iris_groups_to_anatomical_sides,
    reconstruct_iris_centres_from_ipd,
)

__all__ = [
    "CROSSGAZE_CAMERA_MATRIX",
    "CROSSGAZE_DIST_COEFFS",
    "CROSSGAZE_IMAGE_HEIGHT_PX",
    "CROSSGAZE_IMAGE_WIDTH_PX",
    "DEFAULT_DECA_ROOT",
    "DEFAULT_DECA_CROP_SCALE",
    "DEFAULT_PNP_MAPPING",
    "FACE_PREPROCESS_CHOICES",
    "FACE_PREPROCESS_DECA",
    "FACE_PREPROCESS_LEGACY",
    "FLAME_LEFT_EYE_CANTHUS_INDICES",
    "FLAME_RIGHT_EYE_CANTHUS_INDICES",
    "MEDIAPIPE_PNP_LANDMARK_INDICES",
    "PNP_GEOMETRY_VERSION",
    "DecaFlameConfig",
    "DecaFlameExtractor",
    "DecaFlameOutput",
    "head_local_pose_parameters",
    "FaceCropTransform",
    "PnpCamera",
    "PnpConfig",
    "PnpFaceDepthResult",
    "PnpPointMapping",
    "ScaleEstimate",
    "compute_scale_estimate",
    "compute_eye_canthus_midpoints",
    "build_face_crop_transform",
    "prepare_deca_face_image",
    "solve_pnp_face_depth",
    "validate_crossgaze_image_size",
    "IrisIpdReconstruction",
    "assign_iris_groups_to_anatomical_sides",
    "reconstruct_iris_centres_from_ipd",
]
