"""Offline geometry components for generating gaze depth priors."""

from .deca_flame import (
    DEFAULT_DECA_ROOT,
    FLAME_LEFT_EYE_CENTER_VERTEX,
    FLAME_RIGHT_EYE_CENTER_VERTEX,
    DecaFlameConfig,
    DecaFlameExtractor,
    DecaFlameOutput,
)
from .face_preprocess import (
    DEFAULT_DECA_CROP_SCALE,
    FACE_PREPROCESS_CHOICES,
    FACE_PREPROCESS_DECA,
    FACE_PREPROCESS_LEGACY,
    FaceCropTransform,
    build_face_crop_transform,
    prepare_deca_face_image,
)
from .pnp import (
    CROSSGAZE_CAMERA_MATRIX,
    CROSSGAZE_DIST_COEFFS,
    DEFAULT_PNP_MAPPING,
    FLAME_LEFT_EYE_CANTHUS_INDICES,
    FLAME_RIGHT_EYE_CANTHUS_INDICES,
    PnpCamera,
    PnpConfig,
    PnpFaceDepthResult,
    PnpPointMapping,
    ScaleEstimate,
    compute_eye_canthus_midpoints,
    compute_scale_estimate,
    solve_pnp_face_depth,
)

__all__ = [
    "CROSSGAZE_CAMERA_MATRIX",
    "CROSSGAZE_DIST_COEFFS",
    "DEFAULT_DECA_ROOT",
    "DEFAULT_DECA_CROP_SCALE",
    "DEFAULT_PNP_MAPPING",
    "FACE_PREPROCESS_CHOICES",
    "FACE_PREPROCESS_DECA",
    "FACE_PREPROCESS_LEGACY",
    "FLAME_LEFT_EYE_CENTER_VERTEX",
    "FLAME_LEFT_EYE_CANTHUS_INDICES",
    "FLAME_RIGHT_EYE_CENTER_VERTEX",
    "FLAME_RIGHT_EYE_CANTHUS_INDICES",
    "DecaFlameConfig",
    "DecaFlameExtractor",
    "DecaFlameOutput",
    "FaceCropTransform",
    "PnpCamera",
    "PnpConfig",
    "PnpFaceDepthResult",
    "PnpPointMapping",
    "ScaleEstimate",
    "compute_scale_estimate",
    "compute_eye_canthus_midpoints",
    "build_face_crop_transform",
    "prepare_deca_face_image",
    "solve_pnp_face_depth",
]
